spring.application.name=SpringDb


#Conexion con Db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/CursoSpringDB
spring.datasource.username=postgres
spring.datasource.password=24je11fg91

#Permite los cambios en base de datos
spring.jpa.hibernate.ddl-auto=update

#Ver las intrucciones de SQL
spring.jpa.show-sql=true